---
- hosts: localhost

  vars:
    homebrew_taps:
      - homebrew/cask-fonts
      - homebrew/cask-drivers
      - homebrew/cask-versions
      - AdoptOpenJDK/openjdk
      - gromgit/homebrew-fuse


    homebrew_installed_packages:
      - arduino-cli
      - bat
      - binwalk
      - cscope
      - ctags
      - docker
      - dockutil
      - esptool
      - flashrom
      - fzf
      - gnuplot
      - gradle
      - hackrf
      - hexyl
      - ipython
      - minipro
      - ntfs-3g-mac
      - reattach-to-user-namespace
      - rg
      - stlink
      - stm32flash
      - svn
      - tmux
      - ubertooth
      - vim
      - wget
      - youtube-dl
      - zsh
      - zsh-git-prompt

    homebrew_cask_apps:
      - adoptopenjdk/openjdk/adoptopenjdk8
      - bettertouchtool
      - beyond-compare
      - blender
      - cubicsdr
      - dash4
      - docker
      - dozer
      - firefox
      - font-cascadia-code
      - font-dejavu
      - font-dejavu-sans-mono-nerd-font
      - font-fira-code
      - font-iosevka-nerd-font
      - font-menlo-for-powerline
      - font-mononoki
      - font-profont-nerd-font
      - font-terminus
      - font-ubuntu-mono
      - freac
      - ghidra
      - gimp
      - google-drive
      - gqrx
      - iina
      - istat-menus
      - iterm2
      - keepassxc
      - little-snitch
      - macfuse
      - macvim
      - nordic-nrf-command-line-tools
      - nordic-nrf-connect
      - osxfuse
      - outguess
      - protonvpn
      - segger-jlink
      - skype
      - spotify
      - steam
      - teamviewer
      - vagrant
      - virtualbox
      - virtualbox-extension-pack
      - visual-studio-code
      - qbittorrent
      - wireshark

  roles:
    - geerlingguy.mac.homebrew
